"""Recreate migrations

Revision ID: 086d60ad6cbc
Revises:
Create Date: 2025-02-21 01:29:51.378588

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '086d60ad6cbc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
